CREATE PROCEDURE ProcessMonthlyInterest AS
BEGIN
    FOR REC IN (
        SELECT ACCOUNT_ID, ACCOUNT_BALANCE
        FROM ACCOUNTS
        WHERE ACCOUNT_TYPE = 'SAVINGS'
    ) LOOP
        UPDATE ACCOUNTS
        SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + (ACCOUNT_BALANCE * 0.01)
        WHERE ACCOUNT_ID = REC.ACCOUNT_ID;

        DBMS_OUTPUT.PUT_LINE('INTEREST ADDED TO ACCOUNT ID: ' || REC.ACCOUNT_ID);
    END LOOP;
    
END;

