CREATE  PROCEDURE UpdateEmployeeBonus (
    P_DEPT_NAME     IN VARCHAR2,
    P_BONUS_PERCENT IN NUMBER
) AS
BEGIN
    FOR REC IN (
        SELECT EMPLOYEE_ID, SALARY
        FROM EMPLOYEES
        WHERE DEPARTMENT_NAME = P_DEPT_NAME
    ) LOOP
        UPDATE EMPLOYEES
        SET SALARY = SALARY + (SALARY * P_BONUS_PERCENT / 100)
        WHERE EMPLOYEE_ID = REC.EMPLOYEE_ID;

        DBMS_OUTPUT.PUT_LINE('BONUS APPLIED TO EMPLOYEE ID: ' || REC.EMPLOYEE_ID);
    END LOOP;

    COMMIT;
END;
