CREATE PROCEDURE TransferFunds (
    P_FROM_ID IN NUMBER,
    P_TO_ID   IN NUMBER,
    P_AMOUNT  IN NUMBER
) AS
    V_FROM_BALANCE NUMBER;
BEGIN

    SELECT ACCOUNT_BALANCE INTO V_FROM_BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = P_FROM_ID;
    IF V_FROM_BALANCE < P_AMOUNT THEN
        RAISE_APPLICATION_ERROR(-20001, 'INSUFFICIENT BALANCE IN SOURCE ACCOUNT');
    END IF;
    UPDATE ACCOUNTS
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE - P_AMOUNT
    WHERE ACCOUNT_ID = P_FROM_ID;
    UPDATE ACCOUNTS
    SET ACCOUNT_BALANCE = ACCOUNT_BALANCE + P_AMOUNT
    WHERE ACCOUNT_ID = P_TO_ID;

    DBMS_OUTPUT.PUT_LINE('TRANSFERRED ' || P_AMOUNT || ' FROM ACCOUNT ' || P_FROM_ID || ' TO ACCOUNT ' || P_TO_ID);

END;

