SET SERVEROUTPUT ON;
-- SCENARIO 1: APPLY 1% DISCOUNT TO INTEREST RATES FOR CUSTOMERS ABOVE 60
BEGIN
    FOR REC IN (SELECT NAME ,CUSTOMER_ID, INTEREST_RATE FROM CUSTOMERS WHERE AGE > 60) LOOP
        UPDATE CUSTOMERS
        SET INTEREST_RATE = INTEREST_RATE - 1
        WHERE CUSTOMER_ID = REC.CUSTOMER_ID;
        DBMS_OUTPUT.PUT_LINE('INTEREST RATE UPDATED FOR CUSTOMER ID: ' || REC.NAME);
    END LOOP;
    COMMIT;
END;

SELECT * FROM CUSTOMERS;--DONT RUN WITH THE ANNONYMOUS BLOCK JUST RUN AFTER RUNNING THE BLOCK TO SEE HTE ENTIRE TABLE



-- SCENARIO 2: PROMOTE CUSTOMERS TO VIP IF BALANCE > 10000

BEGIN
    FOR REC IN (SELECT NAME ,CUSTOMER_ID FROM CUSTOMERS WHERE BALANCE > 10000) LOOP
        UPDATE CUSTOMERS
        SET VIP = 'Y'
        WHERE CUSTOMER_ID = REC.CUSTOMER_ID;

        DBMS_OUTPUT.PUT_LINE( REC.NAME || ' PROMOTED TO VIP.');
    END LOOP;

    COMMIT;
END;

SELECT * FROM CUSTOMERS;--DONT RUN WITH THE ANNONYMOUS BLOCK JUST RUN AFTER RUNNING THE BLOCK TO SEE HTE ENTIRE TABLE

-- SCENARIO 3: SEND REMINDERS FOR LOANS DUE IN NEXT 30 DAYS
BEGIN
    FOR REC IN (
        SELECT CUSTOMER_ID, NAME, DUE_DATE 
        FROM CUSTOMERS 
        WHERE DUE_DATE BETWEEN SYSDATE AND SYSDATE + 30
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('REMINDER: ' || REC.NAME || 
                             ' CUSTOMER ID: ' || REC.CUSTOMER_ID || 
                             ' HAS A LOAN DUE ON ' || TO_CHAR(REC.DUE_DATE, 'DD-MON-YYYY'));
    END LOOP;
END;

